# Generated by Django 3.2.25 on 2026-05-11 21:58

from django.db import migrations, models
import manga.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('poster_url', models.URLField()),
                ('generos', models.JSONField(default=list)),
                ('capitulos', models.IntegerField()),
                ('estado', models.CharField(choices=[('EM', 'En emision'), ('FI', 'Finalizado'), ('PA', 'En pausa')], default='EM', max_length=2)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.JSONField(default=list, validators=[manga.models.validador_review])),
                ('id_autor', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
