# Generated by Django 3.2.25 on 2026-05-10 19:19

import anime.models
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('episodes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('genres', djongo.models.fields.JSONField()),
                ('reviews', djongo.models.fields.ArrayField(blank=True, default=list, model_container=anime.models.Review)),
                ('characters', djongo.models.fields.ArrayField(blank=True, default=list, model_container=anime.models.Character)),
                ('stats', djongo.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
