# Generated by Django 3.2.25 on 2026-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='poster_url',
            field=models.URLField(default='https://i.imgur.com/QvUUowX.jpeg'),
        ),
    ]
