# Generated by Django 3.2.25 on 2026-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('noticia', 'Noticia'), ('estreno', 'Estreno'), ('resena', 'Reseña'), ('recomendacion', 'Recomendación'), ('lista', 'Lista / Top'), ('entrevista', 'Entrevista')], default='noticia', max_length=20)),
                ('titulo', models.CharField(max_length=500)),
                ('resumen', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='comunidad/')),
                ('etiquetas', models.CharField(blank=True, max_length=300)),
                ('puntuacion', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('fecha_estreno', models.DateField(blank=True, null=True)),
                ('anime_nombre', models.CharField(blank=True, max_length=200)),
                ('manga_nombre', models.CharField(blank=True, max_length=200)),
                ('destacada', models.BooleanField(default=False)),
                ('publicada', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
